import { VowType } from '../App';
import { Language } from './translations';

export interface VowData {
  title: string;
  vows: string[];
}

const vowsDataRu: Record<VowType, VowData> = {
  '10-principles': {
    title: '10 этических принципов',
    vows: [
      'Сохранение жизни',
      'Уважение чужой собственности',
      'Уважение отношений других людей',
      'Говорить правду',
      'Соединяющая речь',
      'Мягкая речь',
      'Говорить о важном',
      'Радоваться успехам других',
      'Сочувствие неудачам других людей',
      'Сохранение правильного мировоззрения',
    ],
  },
  'freedom': {
    title: 'Обеты прибежища',
    vows: [
      'После принятия прибежища в Будде не искать прибежища в мирских объектах и божествах',
      'После принятия прибежища в Дхарме не наносить вреда никаким живым существам',
      'После принятия прибежища в Сангхе избегать близкого общения с людьми, не разделяющими веру в Путь',
      'Почитать любое изображение Будды как самого Будду',
      'Почитать любой написанный текст или даже одну букву как саму Дхарму',
      'Почитать даже лоскут шафрановой накидки как саму Сангху',
      'Принимать прибежище снова и снова, помня о благих качествах объектов прибежища',
      'Предлагать первую часть любой еды и питья объектам прибежища',
      'Поощрять других принимать прибежище',
      'Принимать прибежище три раза утром и три раза вечером',
      'Полностью полагаться на объекты прибежища во время любых действий',
      'Не отрекаться от Трех Драгоценностей, даже ценою жизни',
    ],
  },
  'bodhisattva': {
    title: 'Обеты бодхисаттвы',
    vows: [
      'Не восхвалять себя в корыстных целях',
      'Не порицать и не критиковать других в корыстных целях',
      'Не отказывать в Дхарме из чувства собственности',
      'Не отказывать в материальной помощи из чувства собственничества',
      'Принимать чьи-либо извинения',
      'Не наносить удары другому человеку',
      'Не отрицать учение махаяны как не данное Буддой',
      'Не обучать ложной Дхарме',
      'Не красть того, что принадлежит Трем Драгоценностям',
      'Не отрекаться от Дхармы путем отрицания любого пути',
      'Не лишать монахов их монашеского одеяния и статуса',
      'Не совершать тягчайших деяний',
      'Не разрушать селения, города и области',
      'Не давать учение о пустоте неподготовленному человеку',
      'Не отворачивать человека от стремления к просветлению',
      'Не отказываться от стремления к просветлению',
    ],
  },
  'secret': {
    title: 'Секретные обеты',
    vows: [
      'Поддерживать чистую самаю с гуру',
      'Не нарушать обещания',
      'Относиться к ваджрным братьям и сестрам с любовью',
      'Не оставлять бодхичитту',
      'Не раскрывать тайные учения',
      'Практиковать божество',
      'Делать подношения',
      'Соблюдать тантрические обязательства',
      'Медитировать на пустоту',
      'Служить на благо существ',
    ],
  },
  'nuns': {
    title: 'Обеты монахинь',
    vows: [
      'Соблюдать целомудрие',
      'Не красть',
      'Не убивать',
      'Не лгать о духовных достижениях',
      'Следовать монашескому распорядку',
      'Носить монашеские одежды',
      'Практиковать смирение',
      'Жить в простоте',
      'Изучать священные тексты',
      'Служить сангхе',
    ],
  },
  'monks': {
    title: 'Обеты монахов',
    vows: [
      'Соблюдать целомудрие',
      'Не красть',
      'Не убивать',
      'Не лгать о духовных достижениях',
      'Следовать монашескому распорядку',
      'Носить монашеские одежды',
      'Практиковать смирение',
      'Жить в простоте',
      'Изучать священные тексты',
      'Служить сангхе',
    ],
  },
};

const vowsDataEn: Record<VowType, VowData> = {
  '10-principles': {
    title: '10 Ethical Principles',
    vows: [
      'Not to harm others',
      'Respect the property of others',
      'Not to destroy relationships',
      'Speak gently',
      'Speak meaningfully',
      'Speak truthfully',
      'Rejoice in the success of others',
      'Feel gratitude',
      'Develop wisdom',
      'Practice compassion',
    ],
  },
  'freedom': {
    title: 'Refuge Vows',
    vows: [
      'After taking refuge in Buddha, do not seek refuge in worldly objects and deities',
      'After taking refuge in Dharma, do not harm any living beings',
      'After taking refuge in Sangha, avoid close association with those who do not share faith in the Path',
      'Honor any image of Buddha as Buddha himself',
      'Honor any written text or even a single letter as the Dharma itself',
      'Honor even a scrap of saffron robe as the Sangha itself',
      'Take refuge again and again, remembering the qualities of the objects of refuge',
      'Offer the first portion of any food and drink to the objects of refuge',
      'Encourage others to take refuge',
      'Take refuge three times in the morning and three times in the evening',
      'Completely rely on the objects of refuge in all actions',
      'Do not renounce the Three Jewels, even at the cost of life',
    ],
  },
  'bodhisattva': {
    title: 'Bodhisattva Vows',
    vows: [
      'Do not praise yourself for selfish purposes',
      'Do not criticize others for selfish purposes',
      'Do not refuse to give Dharma out of possessiveness',
      'Do not refuse material help out of possessiveness',
      'Accept others\' apologies',
      'Do not strike another person',
      'Do not deny Mahayana teachings as not given by Buddha',
      'Do not teach false Dharma',
      'Do not steal what belongs to the Three Jewels',
      'Do not renounce Dharma by denying any path',
      'Do not deprive monastics of their robes and status',
      'Do not commit grave actions',
      'Do not destroy villages, cities and regions',
      'Do not teach emptiness to unprepared people',
      'Do not turn a person away from aspiration to enlightenment',
      'Do not abandon the aspiration to enlightenment',
    ],
  },
  'secret': {
    title: 'Secret Vows',
    vows: [
      'Maintain pure samaya with the guru',
      'Not to break promises',
      'Treat vajra brothers and sisters with love',
      'Not to abandon bodhicitta',
      'Not to reveal secret teachings',
      'Practice the deity',
      'Make offerings',
      'Keep tantric commitments',
      'Meditate on emptiness',
      'Serve for the benefit of beings',
    ],
  },
  'nuns': {
    title: 'Nun Vows',
    vows: [
      'Maintain celibacy',
      'Not to steal',
      'Not to kill',
      'Not to lie about spiritual attainments',
      'Follow the monastic schedule',
      'Wear monastic robes',
      'Practice humility',
      'Live simply',
      'Study sacred texts',
      'Serve the sangha',
    ],
  },
  'monks': {
    title: 'Monk Vows',
    vows: [
      'Maintain celibacy',
      'Not to steal',
      'Not to kill',
      'Not to lie about spiritual attainments',
      'Follow the monastic schedule',
      'Wear monastic robes',
      'Practice humility',
      'Live simply',
      'Study sacred texts',
      'Serve the sangha',
    ],
  },
};

export function getVowData(vowType: VowType, language: Language = 'ru'): VowData {
  return language === 'en' ? vowsDataEn[vowType] : vowsDataRu[vowType];
}
