import { StyleSheet } from 'react-native';
import { darkTheme } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F2ED',
  },
  gradient: {
    ...StyleSheet.absoluteFillObject,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 20,
  },
  greeting: {
    fontSize: 28,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
  },
  username: {
    fontWeight: '700' as const,
  },
  bottomTabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    paddingTop: 12,
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
  },
  bottomTabShadow: {
    position: 'absolute',
    top: -10,
    left: 0,
    right: 0,
    height: 10,
  },
  bottomTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    gap: 4,
  },
  bottomTabLabel: {
    fontSize: 10,
    fontWeight: '500' as const,
    color: '#5A6A66',
  },
  bottomTabLabelActive: {
    color: darkTheme.colors.primary,
    fontWeight: '600' as const,
  },
  adminBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(107, 142, 127, 0.15)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: darkTheme.colors.primary,
  },
  adminText: {
    color: darkTheme.colors.primary,
    fontWeight: '600' as const,
    fontSize: 16,
  },
  chipsSection: {
    marginBottom: 24,
  },
  chipsSectionLarge: {
    maxWidth: 800,
  },
  chipsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  chipsSectionTitle: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
  },
  chipsSectionTitleLarge: {
    fontSize: 22,
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(107, 142, 127, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipsScrollWrapper: {
    position: 'relative',
    marginHorizontal: -20,
  },
  chipsScrollView: {
    flexGrow: 0,
  },
  chipsScrollContent: {
    paddingLeft: 20,
    paddingRight: 8,
    gap: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chipsSpacer: {
    width: 30,
  },
  chipsFadeRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 40,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkTheme.colors.primary,
    borderRadius: 20,
    paddingVertical: 8,
    paddingLeft: 16,
    paddingRight: 12,
    gap: 8,
    flexShrink: 0,
  },
  chipSmall: {
    paddingVertical: 6,
    paddingLeft: 12,
    paddingRight: 10,
    gap: 6,
  },
  chipText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: '#FFFFFF',
  },
  chipTextSmall: {
    fontSize: 12,
  },
  chipRemove: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vowCardsContainer: {
    gap: 16,
  },
  vowCardsContainerLarge: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  vowCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 24,
    padding: 20,
    minHeight: 170,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  vowCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  vowNumberContainer: {},
  vowNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vowNumberText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },
  vowCategoryBadge: {
    backgroundColor: '#F0EBE3',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  vowCategoryText: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: darkTheme.colors.textSecondary,
  },
  vowText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
    marginBottom: 20,
    lineHeight: 26,
  },
  vowActions: {
    flexDirection: 'row',
    gap: 12,
  },
  keepButton: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  brokenButton: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  actionButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 8,
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  expandedForm: {
    marginTop: 8,
  },
  keepInfoBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(127, 168, 143, 0.15)',
    borderRadius: 16,
    padding: 16,
    gap: 12,
    marginBottom: 16,
  },
  keepInfoText: {
    flex: 1,
    fontSize: 14,
    color: '#5A7A6D',
    lineHeight: 20,
  },
  brokenInfoBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(197, 165, 114, 0.15)',
    borderRadius: 16,
    padding: 16,
    gap: 12,
    marginBottom: 16,
  },
  brokenInfoText: {
    flex: 1,
    fontSize: 14,
    color: '#8B6A4E',
    lineHeight: 20,
  },
  antidoteLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
    marginBottom: 12,
  },
  antidoteTagsWrapper: {
    position: 'relative',
    marginBottom: 16,
    marginHorizontal: -20,
  },
  antidoteTagsScroll: {
    flexGrow: 0,
  },
  antidoteTagsContent: {
    paddingLeft: 20,
    paddingRight: 8,
    gap: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  antidoteTagsSpacer: {
    width: 40,
  },
  antidoteFadeRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 50,
  },
  antidoteTag: {
    backgroundColor: 'rgba(197, 165, 114, 0.15)',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#C5A572',
  },
  antidoteTagText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: '#8B6A4E',
  },
  noteInput: {
    backgroundColor: '#F8F5F0',
    borderRadius: 16,
    padding: 16,
    fontSize: 15,
    color: darkTheme.colors.text,
    minHeight: 80,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#E8E1D5',
    marginBottom: 16,
  },
  formActions: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E8E1D5',
  },
  cancelButtonText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: darkTheme.colors.textSecondary,
  },
  saveButton: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  saveButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 8,
  },
  saveButtonText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 24,
    padding: 48,
    borderWidth: 2,
    borderColor: '#E8E1D5',
    borderStyle: 'dashed',
  },
  emptyStateLarge: {
    maxWidth: 500,
    alignSelf: 'center',
  },
  emptyStateText: {
    fontSize: 16,
    color: darkTheme.colors.textMuted,
    marginTop: 16,
    textAlign: 'center',
  },
  emptyStateTextSmall: {
    fontSize: 14,
  },
  vowCardSubmitted: {
    opacity: 0.95,
  },
  notifTimeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(197, 165, 114, 0.12)',
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 7,
    marginRight: 4,
  },
  notifTimeBadgeText: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: '#C5A572',
  },
  timeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginLeft: 'auto',
  },
  timeBadgeText: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: darkTheme.colors.textMuted,
  },
  submittedView: {
    gap: 12,
  },
  infoBoxKept: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(127, 168, 143, 0.15)',
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  infoBoxKeptText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500' as const,
    color: '#5A7A6D',
  },
  infoBoxBroken: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(184, 92, 79, 0.12)',
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  infoBoxBrokenText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500' as const,
    color: '#A04A3E',
  },
  infoBoxAntidote: {
    backgroundColor: 'rgba(197, 165, 114, 0.15)',
    borderRadius: 16,
    padding: 16,
    gap: 6,
  },
  antidoteLabelSmall: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#8B6A4E',
  },
  antidoteValueText: {
    fontSize: 14,
    color: '#6B5A3E',
    lineHeight: 20,
  },
  noteDisplay: {
    backgroundColor: 'rgba(107, 142, 127, 0.08)',
    borderRadius: 12,
    padding: 12,
  },
  noteDisplayText: {
    fontSize: 14,
    fontStyle: 'italic',
    color: darkTheme.colors.textSecondary,
    lineHeight: 20,
  },
  historyContainer: {
    gap: 20,
  },
  historyCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 12,
  },
  historyCardOverdue: {
    borderWidth: 1,
    borderColor: '#C5A572',
    backgroundColor: 'rgba(197, 165, 114, 0.08)',
  },
  historyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  historyDateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginLeft: 'auto',
  },
  historyDateText: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: darkTheme.colors.textMuted,
  },
  historyVowText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
    marginBottom: 12,
    lineHeight: 22,
  },
  historyInfoBoxKept: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(127, 168, 143, 0.12)',
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  historyInfoBoxKeptText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500' as const,
    color: '#5A7A6D',
  },
  historyInfoBoxBroken: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(184, 92, 79, 0.1)',
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  historyInfoBoxBrokenText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500' as const,
    color: '#A04A3E',
  },
  historyInfoBoxAntidote: {
    backgroundColor: 'rgba(197, 165, 114, 0.12)',
    borderRadius: 12,
    padding: 12,
    gap: 4,
    marginTop: 8,
  },
  historyActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  historyActionButton: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  historyActionGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 6,
  },
  historyActionText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  historyPostponeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: '#E8E1D5',
  },
  historyPostponeText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: darkTheme.colors.textSecondary,
  },
  overdueLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  overdueLabelText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#C5A572',
  },
  overdueSection: {
    marginBottom: 24,
  },
  overdueSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  overdueSectionTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#8B6A4E',
  },
  regularHistorySection: {
    gap: 0,
  },
  regularHistorySectionTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
    marginBottom: 12,
  },
  antidoteCompletedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(107, 142, 127, 0.12)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  antidoteCompletedText: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: '#6B8E7F',
  },
  emptyHistory: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 24,
    padding: 48,
    marginTop: 20,
  },
  emptyHistoryText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: darkTheme.colors.text,
    marginTop: 16,
  },
  emptyHistorySubtext: {
    fontSize: 14,
    color: darkTheme.colors.textMuted,
    marginTop: 8,
    textAlign: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 48,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 24,
  },
  loadingText: {
    fontSize: 16,
    color: darkTheme.colors.textMuted,
    marginTop: 16,
  },
  historyTabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#E8E1D5',
    borderRadius: 16,
    padding: 4,
    marginBottom: 24,
  },
  historyTab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyTabLeft: {
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  historyTabRight: {
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
  },
  historyTabActive: {
    backgroundColor: darkTheme.colors.primary,
  },
  historyTabText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#5A6A66',
  },
  historyTabTextActive: {
    color: '#FFFFFF',
  },
});
